### ISSUE TITLE
How to document problems?

### ISSUE THREAD

**Issue by LauraWebdev** [bfeber/HLA-NOVR-Script#13]
Hey everyone,
first of all, tremendously wonderful project, I've played through the game already in VR but playing it again with KBM is quite a different experience!

I was wondering how I could document some of the issues I'm encountering playing through the game. Should there just be new issues per problem, are there things that are "out of scope" for this project?

For example: I've noticed that I can't really interact with the upgrade machines, it's such a big thing of the experience that I figured it's already on some list, but I wasn't sure if creating an issue makes sense.

**Comment by bfeber** [comment]
> I was wondering how I could document some of the issues I'm encountering playing through the game. Should there just be new issues per problem, are there things that are "out of scope" for this project?

Sure, create a new issue for each problem/suggestion.

> For example: I've noticed that I can't really interact with the upgrade machines, it's such a big thing of the experience that I figured it's already on some list, but I wasn't sure if creating an issue makes sense.

That's being worked on in the future, but you can still create an issue if you want.

**Comment by LauraWebdev** [comment]
Awesome, thanks!
