### ISSUE TITLE
a3_station_street: Health station and item box not interactable

### ISSUE THREAD

**Issue by LauraWebdev** [bfeber/HLA-NOVR-Script#14]
**Map**
a3_station_street

**Issue**
The objects in this area are not interactable

**Screenshot**
![20230403200944_1](https://user-images.githubusercontent.com/7365286/229811761-f39668ba-bed4-4f85-8c13-fb7f194cc853.jpg)

**Video**
[https://youtu.be/nPnOVqLqXpg](https://youtu.be/nPnOVqLqXpg)

**Comment by bfeber** [comment]
Fixed
