### ISSUE TITLE
pak is corrupt

### ISSUE THREAD

**Issue by Tempus3214** [bfeber/HLA-NOVR-Script#2]
hi, hello, i just installed the new update 2 version but it gives me the error : pak file is corrupt, then it automatically verifies hl alyx, could you please help me out?? i would love to play the game with no vr, thank you!!

**Comment by bfeber** [comment]
Huh, that's weird. Let me try to reproduce it.

**Comment by bfeber** [comment]
Thanks for letting me know! I had to use Git LFS because the VPK was over 100MB, but then the didn't work properly anymore. Should be fixed now.
