### ISSUE TITLE
Instruction or warning

### ISSUE THREAD

**Issue by Smelt1993** [bfeber/HLA-NOVR-Script#36]
I think you should warn that the script breaks the mechanics of the game if you run it in a virtual reality helmet. So that people either make a duplicate of the original files before installing it, or add a folder with the original content to the archive. So that a stupid person (a layman) does not have to do a cache check on Steam afterwards.

p.s

Add more speed for Noclip.

p.s.s

Forgive me my eng.

**Comment by bfeber** [comment]
Fixed with the new installation method
