### ISSUE TITLE
Viewmodel FOV?

### ISSUE THREAD

**Issue by ellie12134** [bfeber/HLA-NOVR-Script#5]
This might not need to be a new feature, but changing the viewmodel fov or just increasing it a bit by default could be good

also is there any way of doing this as of rn? via console? I cant manage to get the console open by using -console

**Comment by Rubyboat1207** [comment]
to open the console, you need to put both `-console -vconsole` into the launch args. Viewmodel fov will not work out of the box, use: `viewmodel_offset_[x,y,z]` instead

**Comment by bfeber** [comment]
I'll move the viewmodels further back in the future, for now use the command above. Changing viewmodel FOV is not possible because it is not rendered separately in HLA.

**Comment by ellie12134** [comment]
> to open the console, you need to put both `-console -vconsole` into the launch args. Viewmodel fov will not work out of the box, use: `viewmodel_offset_[x,y,z]` instead

I have already tried using both console launch args yesterday but neither allowed me to open the console

**Comment by ellie12134** [comment]
> 

I just tried that ,it didnt work either
